# Keep nixos-24.11 up-to-date with changes from upstream and thoughtfull branches.
#
# Difference from upstream should be only thoughtfull branches:
# https://github.com/NixOS/nixpkgs/compare/nixos-24.11...thoughtfull-nix:nixpkgs:nixos-24.11
name: Update nixos-24.11
on:
  push:
    branches:
      - workflows
      - initrd-dhcp-background-24.11
      - fix-tlp-networkmanager-dispatch-24.11
  schedule:
    # every day at midnight Eastern
    - cron: "0 0 * * *"
      timezone: "America/New_York"
  workflow_dispatch:
concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true
jobs:
  update:
    defaults:
      run:
        shell: bash
    name: Update nixos-24.11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: thoughtfull-systems/checkout-then-configure@main
        with:
          ref: nixos-24.11
          fetch-depth: 0
          # Upstream occasionally changes workflows and to pull those changes we need `workflows`
          # write permission which is not possible with the default Github token
          token: ${{secrets.PAT}}
      - name: Add upstream remote
        run: |
          git remote add -t nixos-24.11 --no-tags -f upstream "https://github.com/nixos/nixpkgs.git"
      - name: Merge from upstream
        run: |
          git merge --no-ff upstream/nixos-24.11
      - name: Merge thoughtfull branches
        run: |
          git merge --no-ff origin/workflows
          git merge --no-ff origin/initrd-dhcp-background-24.11
          git merge --no-ff origin/fix-tlp-networkmanager-dispatch-24.11
      - name: Push to origin
        run: |
          git push origin nixos-24.11
